# Generated by Django 5.2.5 on 2025-11-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
        migrations.AlterField(
            model_name="country",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="countries/"),
        ),
        migrations.AlterField(
            model_name="place",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="place/"),
        ),
    ]
