# Generated by Django 5.2.5 on 2025-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=20,
            ),
        ),
    ]
