# Generated by Django 5.2.5 on 2025-11-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
