# Generated by Django 5.2.5 on 2025-11-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0003_trip_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
