# Generated by Django 5.2.5 on 2025-11-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0005_alter_trip_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[("planned", "planned"), ("completed", "completed")],
                default="planned",
                max_length=20,
            ),
        ),
    ]
