# Generated by Django 5.2.5 on 2025-11-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0006_alter_trip_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="budget",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
