# Generated by Django 5.2.5 on 2025-11-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0007_trip_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
