# Generated by Django 5.2.5 on 2025-11-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0008_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
