# Generated by Django 5.2.5 on 2025-11-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0009_remove_customuser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
