# Generated by Django 5.2.5 on 2025-11-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0011_comment_delete_goals"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
