# Generated by Django 5.2.5 on 2025-11-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0012_profile_address_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="First_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
