# Generated by Django 5.2.5 on 2025-12-01 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0013_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="country",
        ),
        migrations.AddField(
            model_name="blog",
            name="place",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="travel_app.place",
            ),
            preserve_default=False,
        ),
    ]
