# Generated by Django 5.2.5 on 2025-12-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0014_remove_blog_country_blog_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
