# Generated by Django 5.2.5 on 2025-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0015_profile_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
