# Generated by Django 5.2.5 on 2025-12-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0016_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
