# Generated by Django 5.2.5 on 2025-12-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0017_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="travel_app.place",
            ),
        ),
    ]
