# Generated by Django 5.2.5 on 2025-12-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0018_alter_blog_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog/")),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_image",
                        to="travel_app.blog",
                    ),
                ),
            ],
        ),
    ]
