# Generated by Django 5.2.5 on 2025-12-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0019_remove_blog_image_blogimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="title",
        ),
    ]
