# Generated by Django 5.2.5 on 2025-12-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0020_remove_blog_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
