# Generated by Django 5.2.5 on 2025-12-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0021_blog_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbadge",
            name="badge",
        ),
        migrations.RemoveField(
            model_name="userbadge",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("blog", "user")},
        ),
        migrations.DeleteModel(
            name="Badge",
        ),
        migrations.DeleteModel(
            name="UserBadge",
        ),
    ]
