# Generated by Django 5.2.5 on 2025-12-21 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_app", "0023_save"),
    ]

    operations = [
        migrations.AlterField(
            model_name="save",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saves",
                to="travel_app.blog",
            ),
        ),
        migrations.AlterField(
            model_name="save",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="save",
            unique_together={("user", "blog")},
        ),
    ]
